# Generated by Django 3.1.7 on 2021-04-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Basliq:')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yazilma Tarixi:')),
                ('confirm', models.BooleanField(default=False, verbose_name='Tamamlanilib?:')),
            ],
        ),
    ]
