# Generated by Django 3.1.7 on 2021-05-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_task_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
    ]
