# Generated by Django 3.1.7 on 2021-05-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_task_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(blank=True, verbose_name='Basliq:'),
        ),
    ]
