# Generated by Django 3.1.7 on 2021-05-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_auto_20210508_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(blank=True, verbose_name='Basliq:'),
        ),
    ]
