# Generated by Django 3.1.7 on 2021-05-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_auto_20210508_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(verbose_name='Basliq:'),
        ),
    ]
